services:
  - type: web
    name: bacheca-automatica
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bacheca-automatica/robot/leggi_circolari.py
    envVars:
      - key: ARGO_USER
        value: davide.marziano.sc26953
      - key: ARGO_PASS
        sync: false
      - key: DB_PASSWORD
        sync: false
